jobs:
  - job: versioncheck
    displayName: "versioncheck"
    pool:
      vmImage: '$(pool_name)'
    workspace:
      clean: all
    steps:
      - script: |
          echo "Checking Docker version..."
          docker --version
        displayName: 'Check Docker Version'
        