jobs:
- job: dockerbuild
  dependsOn: dockerlogin
  displayName: "dockerbuild"
  pool:
    vmImage: '$(pool_name)'
  workspace:
    clean: all
  steps:
  - script: |
      echo "docker build"
      cd $(Build.Repository.LocalPath)/.pipelines/script/docker
      docker build -t $(dockerRegistry)/$(dockerImageName):$(dockerImageTag) .
    displayName: 'Docker Build'
