jobs:
  - job: dockerpush
    dependsOn: dockertest
    displayName: "docker push"
    pool:
      name: '$(pool_name)'
    workspace:
      clean: all
    steps:
    - script: |
        docker push $(dockerRegistry)/$(dockerImageName):$(dockerImageTag)
      displayName: 'Docker Push'